CREATE TABLE comment
(
    comment_id INTEGER IDENTITY,
    post_id    INTEGER NOT NULL CONSTRAINT COMMENT_POST REFERENCES post (post_id),
    user_id    INTEGER NOT NULL CONSTRAINT COMMENT_USER REFERENCES users (user_id),
    content    VARCHAR(2000000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
